apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: video-upload
spec:
  replicas: 1
  selector:
    matchLabels:
      app: video-upload
  template:
    metadata:
      labels:
        app: video-upload
    spec:
        containers:
        - name: video-upload
          image: video-upload
          imagePullPolicy: Never
          command: [
            "./video-upload-svc",
            "--selector=static",
            "--server_address=:8080",
            "--broker_address=:10001"
          ]
          env:
          - name: MINIO_URL
            value: "minio-0:9000"
          - name: MINIO_ACCESS_KEY
            value: "minio"
          - name: MINIO_SECRET_KEY
            value: "minio123"
          - name: UPDATED_AT
            value: "Fri Apr 13 16:41:23 PDT 2018"
          ports:
          - containerPort: 8080
            name: upload-port
