apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: video-upload
spec:
  replicas: 3
  selector:
    matchLabels:
      app: video-upload
  template:
    metadata:
      labels:
        app: video-upload
      annotations:
        prometheus.io/scrape: "true"
    spec:
        containers:
        - name: video-upload
          image: video_upload
          imagePullPolicy: Never
          env:
          - name: MINIO_URL
            value: "192.168.1.74:30366"
          - name: MINIO_ACCESS_KEY
            value: "minio"
          - name: MINIO_SECRET_KEY
            value: "minio123"
          - name: PG_HOST
            value: "postgres-postgresql"
          - name: PG_USER
            value: "postgres"
          - name: PG_PASSWORD
            value: "postgres123"
          - name: UPDATED_AT
            value: "Sat May 26 13:42:57 PDT 2018"
          - name:  MICRO_REGISTRY
            value:  kubernetes
          - name: MICRO_SELECTOR
            value: cache
          - name: MICRO_SERVER_ADDRESS
            value: 0.0.0.0:8080
          - name: MICRO_BROKER_ADDRESS
            value: 0.0.0.0:10001
          - name: JAEGER_SERVICE_NAME
            value: video-upload-svc
          - name: JAEGER_AGENT_HOST
            value: jaeger-agent
          - name: JAEGER_SAMPLER_TYPE
            value: const
          - name: JAEGER_SAMPLER_PARAM
            value: "1"
          - name: JAEGER_REPORTER_LOG_SPANS
            value: "true"
          - name: OPENTRACING_METRICS_EXPORTER_HTTP_PATH
            value: "/metrics"
          ports:
          - name: upload-port
            containerPort: 8080
          - name: prometheus
            containerPort: 9090
