apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: video-upload
spec:
  replicas: 1
  selector:
    matchLabels:
      app: video-upload
  template:
    metadata:
      labels:
        app: video-upload
    spec:
        containers:
        - name: video-upload
          image: video_upload
          imagePullPolicy: Never
          env:
          - name: MINIO_URL
            value: "minio:9000"
          - name: MINIO_ACCESS_KEY
            value: "minio"
          - name: MINIO_SECRET_KEY
            value: "minio123"
          - name: UPDATED_AT
            value: "Mon May 14 19:10:53 PDT 2018"
          - name:  MICRO_REGISTRY
            value:  kubernetes
          - name: MICRO_SELECTOR
            value: cache
          - name: MICRO_SERVER_ADDRESS
            value: 0.0.0.0:8080
          - name: MICRO_BROKER_ADDRESS
            value: 0.0.0.0:10001
          ports:
          - containerPort: 8080
            name: upload-port