// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/upload.proto

/*
Package video_upload is a generated protocol buffer package.

It is generated from these files:
	proto/upload.proto

It has these top-level messages:
	Request
	Response
	UploadRequest
	UploadResponse
	PropertyRequest
	PropertyResponse
	UploadFinishRequest
	UploadFinishResponse
*/
package video_upload

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Request struct {
	Filename string `protobuf:"bytes,1,opt,name=filename" json:"filename,omitempty"`
}

func (m *Request) Reset()                    { *m = Request{} }
func (m *Request) String() string            { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()               {}
func (*Request) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Request) GetFilename() string {
	if m != nil {
		return m.Filename
	}
	return ""
}

type Response struct {
	PresignedUrl string `protobuf:"bytes,1,opt,name=presigned_url,json=presignedUrl" json:"presigned_url,omitempty"`
}

func (m *Response) Reset()                    { *m = Response{} }
func (m *Response) String() string            { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()               {}
func (*Response) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Response) GetPresignedUrl() string {
	if m != nil {
		return m.PresignedUrl
	}
	return ""
}

type UploadRequest struct {
	Filename    string `protobuf:"bytes,1,opt,name=filename" json:"filename,omitempty"`
	Title       string `protobuf:"bytes,2,opt,name=title" json:"title,omitempty"`
	Description string `protobuf:"bytes,3,opt,name=description" json:"description,omitempty"`
}

func (m *UploadRequest) Reset()                    { *m = UploadRequest{} }
func (m *UploadRequest) String() string            { return proto.CompactTextString(m) }
func (*UploadRequest) ProtoMessage()               {}
func (*UploadRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *UploadRequest) GetFilename() string {
	if m != nil {
		return m.Filename
	}
	return ""
}

func (m *UploadRequest) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *UploadRequest) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

type UploadResponse struct {
	Id           string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	PresignedUrl string `protobuf:"bytes,2,opt,name=presigned_url,json=presignedUrl" json:"presigned_url,omitempty"`
}

func (m *UploadResponse) Reset()                    { *m = UploadResponse{} }
func (m *UploadResponse) String() string            { return proto.CompactTextString(m) }
func (*UploadResponse) ProtoMessage()               {}
func (*UploadResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *UploadResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *UploadResponse) GetPresignedUrl() string {
	if m != nil {
		return m.PresignedUrl
	}
	return ""
}

type PropertyRequest struct {
	Filename    string `protobuf:"bytes,1,opt,name=filename" json:"filename,omitempty"`
	Title       string `protobuf:"bytes,2,opt,name=title" json:"title,omitempty"`
	Description string `protobuf:"bytes,3,opt,name=description" json:"description,omitempty"`
}

func (m *PropertyRequest) Reset()                    { *m = PropertyRequest{} }
func (m *PropertyRequest) String() string            { return proto.CompactTextString(m) }
func (*PropertyRequest) ProtoMessage()               {}
func (*PropertyRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *PropertyRequest) GetFilename() string {
	if m != nil {
		return m.Filename
	}
	return ""
}

func (m *PropertyRequest) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *PropertyRequest) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

type PropertyResponse struct {
	Id       string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Filepath string `protobuf:"bytes,2,opt,name=filepath" json:"filepath,omitempty"`
}

func (m *PropertyResponse) Reset()                    { *m = PropertyResponse{} }
func (m *PropertyResponse) String() string            { return proto.CompactTextString(m) }
func (*PropertyResponse) ProtoMessage()               {}
func (*PropertyResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *PropertyResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *PropertyResponse) GetFilepath() string {
	if m != nil {
		return m.Filepath
	}
	return ""
}

type UploadFinishRequest struct {
	Id string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
}

func (m *UploadFinishRequest) Reset()                    { *m = UploadFinishRequest{} }
func (m *UploadFinishRequest) String() string            { return proto.CompactTextString(m) }
func (*UploadFinishRequest) ProtoMessage()               {}
func (*UploadFinishRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *UploadFinishRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type UploadFinishResponse struct {
}

func (m *UploadFinishResponse) Reset()                    { *m = UploadFinishResponse{} }
func (m *UploadFinishResponse) String() string            { return proto.CompactTextString(m) }
func (*UploadFinishResponse) ProtoMessage()               {}
func (*UploadFinishResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func init() {
	proto.RegisterType((*Request)(nil), "video_upload.Request")
	proto.RegisterType((*Response)(nil), "video_upload.Response")
	proto.RegisterType((*UploadRequest)(nil), "video_upload.UploadRequest")
	proto.RegisterType((*UploadResponse)(nil), "video_upload.UploadResponse")
	proto.RegisterType((*PropertyRequest)(nil), "video_upload.PropertyRequest")
	proto.RegisterType((*PropertyResponse)(nil), "video_upload.PropertyResponse")
	proto.RegisterType((*UploadFinishRequest)(nil), "video_upload.UploadFinishRequest")
	proto.RegisterType((*UploadFinishResponse)(nil), "video_upload.UploadFinishResponse")
}

func init() { proto.RegisterFile("proto/upload.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 333 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x53, 0x4d, 0x4f, 0x02, 0x31,
	0x14, 0x94, 0x35, 0x22, 0x3c, 0x01, 0x4d, 0x45, 0x42, 0xd6, 0x8f, 0x60, 0x0d, 0x89, 0x27, 0x48,
	0xe4, 0x6a, 0xbc, 0x69, 0xe2, 0xcd, 0x60, 0x90, 0x23, 0x41, 0xf6, 0x29, 0x2f, 0xa9, 0xdb, 0xda,
	0x16, 0x13, 0x7f, 0x9f, 0x7f, 0xcc, 0xb8, 0xed, 0xae, 0xbb, 0x08, 0xc6, 0x8b, 0xc7, 0x37, 0x33,
	0x9d, 0x99, 0x7d, 0xdd, 0x02, 0x53, 0x5a, 0x5a, 0xd9, 0x5f, 0x28, 0x21, 0xa7, 0x51, 0x2f, 0x19,
	0x58, 0xed, 0x8d, 0x22, 0x94, 0x13, 0x87, 0xf1, 0x2e, 0x6c, 0x0f, 0xf1, 0x75, 0x81, 0xc6, 0xb2,
	0x10, 0x2a, 0x4f, 0x24, 0x30, 0x9e, 0xbe, 0x60, 0xbb, 0xd4, 0x29, 0x9d, 0x57, 0x87, 0xd9, 0xcc,
	0xfb, 0x50, 0x19, 0xa2, 0x51, 0x32, 0x36, 0xc8, 0xce, 0xa0, 0xae, 0x34, 0x1a, 0x7a, 0x8e, 0x31,
	0x9a, 0x2c, 0xb4, 0xf0, 0xe2, 0x5a, 0x06, 0x8e, 0xb4, 0xe0, 0x33, 0xa8, 0x8f, 0x92, 0x84, 0x3f,
	0xb8, 0xb3, 0x26, 0x6c, 0x59, 0xb2, 0x02, 0xdb, 0x41, 0x42, 0xb8, 0x81, 0x75, 0x60, 0x27, 0x42,
	0x33, 0xd3, 0xa4, 0x2c, 0xc9, 0xb8, 0xbd, 0x99, 0x70, 0x79, 0x88, 0x5f, 0x43, 0x23, 0x0d, 0xf1,
	0xdd, 0x1a, 0x10, 0x50, 0xe4, 0xfd, 0x03, 0x8a, 0x7e, 0x76, 0x0d, 0x56, 0x74, 0x45, 0xd8, 0xbd,
	0xd3, 0x52, 0xa1, 0xb6, 0xef, 0xff, 0xd9, 0xf6, 0x0a, 0xf6, 0xbe, 0x63, 0xd6, 0xf4, 0xf5, 0xb9,
	0x6a, 0x6a, 0xe7, 0xde, 0x3e, 0x9b, 0x79, 0x17, 0xf6, 0xdd, 0xd7, 0xde, 0x50, 0x4c, 0x66, 0x9e,
	0x56, 0x5d, 0xb2, 0xe0, 0x2d, 0x68, 0x16, 0x65, 0x2e, 0xea, 0xe2, 0x23, 0x80, 0xb2, 0x23, 0xd8,
	0x25, 0x54, 0xef, 0x07, 0xe9, 0xf9, 0x83, 0x5e, 0xfe, 0x87, 0xe8, 0x79, 0x38, 0x6c, 0x2d, 0xc3,
	0xce, 0x86, 0x6f, 0xb0, 0x5b, 0x80, 0x34, 0x40, 0x20, 0x3b, 0x2c, 0xea, 0x0a, 0x97, 0x1e, 0x1e,
	0xad, 0x26, 0x33, 0xab, 0x31, 0x34, 0xc7, 0x9a, 0x2c, 0x3e, 0x7c, 0xa9, 0xfc, 0x72, 0x08, 0x0d,
	0x3b, 0x2e, 0x9e, 0x5b, 0xba, 0x9d, 0xf0, 0x64, 0x1d, 0x9d, 0x33, 0xae, 0xe5, 0x97, 0xc0, 0x4e,
	0x57, 0x15, 0x29, 0xec, 0x31, 0xe4, 0xbf, 0x49, 0x52, 0xe3, 0xc7, 0x72, 0xf2, 0x88, 0x06, 0x9f,
	0x01, 0x00, 0x00, 0xff, 0xff, 0x53, 0x55, 0xe5, 0x9f, 0x5a, 0x03, 0x00, 0x00,
}
